### ISSUE TITLE
Errors while scraping TV Shows

### ISSUE THREAD

**Issue by NickUK122** [romanvm/kodi.tvmaze#12]
2019-11-14 21:55:48.272 T:12692   ERROR: [metadata.tvmaze (1.0.0)]: **** End diagnostic info ****
2019-11-14 21:55:48.272 T:12692   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: float() argument must be a string or a number
                                            Traceback (most recent call last):
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\metadata.tvmaze\main.py", line 25, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\metadata.tvmaze\libs\actions.py", line 167, in router
                                                get_details(params['url'])
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\metadata.tvmaze\libs\actions.py", line 94, in get_details
                                                list_item = data_utils.add_main_show_info(list_item, show_info)
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\metadata.tvmaze\libs\data_utils.py", line 179, in add_main_show_info
                                                list_item = _set_rating(show_info, list_item)
                                              File "C:\Users\Nick\AppData\Roaming\Kodi\addons\metadata.tvmaze\libs\data_utils.py", line 108, in _set_rating
                                                rating = float(show_info['rating']['average'])
                                            TypeError: float() argument must be a string or a number
                                            -->End of Python script error report<--

**Comment by tvgazza911** [comment]
This has already been fixed in #5.
It's been marked for the v1.0.1 release which hasn't happened yet.

**Comment by romanvm** [comment]
Closing as a duplicate

**Comment by putyn** [comment]
@romanvm any idea when 1.0.1 will be released? I have the same issue 😁

**Comment by romanvm** [comment]
When it's done.
